Repository ColoredCow-Portal/portal, pull requests merged in 2021-07, with the labels that each got.

#210 Updated the function of interviewers for filter of roles
  Modules/User/Entities/User.php
Labels: module : hr, type : bug

#200 Changed application dashboard for all tabs to filter with job id
  resources/views/hr/application/index.blade.php
Labels: status : ready for review

#209 Added Domain Field in create and edit for job
  Modules/HR/Config/config.php
  Modules/HR/Entities/Job.php
  Modules/HR/Http/Controllers/Recruitment/JobController.php
  Modules/HR/Http/Requests/Recruitment/JobRequest.php
  database/migrations/2021_07_16_182228_add_domain_to_hr_jobs.php
  resources/views/hr/job/create.blade.php
  resources/views/hr/job/edit.blade.php
Labels: module : hr, status : ready for review

#208 Added changes to mark expired invoices as red in the mail
  Modules/Invoice/Resources/views/mail/unpaid-invoice-list.blade.php
Labels: status : ready for review
